
# Site settings

url: "http://dansnguyen.github.io" # the base hostname & protocol for your site
# let's you track visitor counts
google_analytics_id: UA-somecode
# point to where this site is hosted on github
github_source_repo: jekyll-portfolio/jekyll-portfolio.github.io

###########################################
# Meta stuff
# this stuff shows up in your site's search results/facebook snippet

title: CoLab Show 	
description: "do you even watch our show"
meta_thumbnail_url: https://www.facebook.com/1014044825279084/photos/a.1014045091945724.1073741825.1014044825279084/1014045098612390/?type=1&theater
favicon_ico: /images/site/something.ico



### These things will show up in your footer
twitter_id: colabshow
instagram_id: colabshow
youtube_id: colabshow

about_url: /about/
contact_url: "/about#contact"
email: colabshow@gmail.com

#######################################

## You probably don't want to mess with this stuff
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /posts/:title
sass:
    sass_dir: assets/_sass

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
